# YOUR NAME OR TITLE OF YOUR SITE
name: Meowphine

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Meowphine. I love voice acting and improving my voice, I also love streaming and posting memes and shenanigans on Twitter!

# YOUR/BRAND IMAGE URL
Image_URL: https://i.imgur.com/MgBwl8i.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://i.imgur.com/pWITYp7.png

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com/mowfeen/
    Username: mowfeen
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv/Meowphine/'
    Username: harsh98trivedi
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # STEAM
  - Name: Steam
    URL: https://steamcommunity.com/id/Fleuf/
    Username: 'Meowphine'
    Color: '#66c0f4'
    Text_Color: '#000000'
    Icon-Class: fab fa-steam

    # DISCORD
  - Name: Discord
    URL: 'https://dsc.gg/maowmaow/'
    Username: Meowphine#6346
    Icon-Class: fab fa-discord
    Color: '#5865F2'
    Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL: https://open.spotify.com/user/31iqwlgkdltr6lita2bpxtwnxady?si=15b19c18039347d3
    Username: Mama Meow
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

     # TIKTOK
  - Name: TikTok
    URL: https://www.tiktok.com/@mowfeen
    Username: mowfeen
    Color: '#FE2C55'
    Icon-Class: fab fa-tiktok

  - Name: Links
    URL: https://github.com/harsh98trivedi/links
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY


# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
